### ISSUE TITLE
Kotlin Multiplatform

### ISSUE THREAD

**Issue by jvanderwee** [ShipBook/ShipBookSDK-Android#10]
Follow up question after reading your [Kotlin Multiplatform blogpost](https://blog.shipbook.io/kotlin-multiplatform-mobile) - do you have any plans to publish a Kotlin Multiplatform library for Shipbook?

**Comment by elishas** [comment]
Thank you for your interest in our Kotlin Multiplatform library for Shipbook! Yes, it is indeed on our roadmap to develop this. We highly value community input, so if you have any suggestions or ideas on how to enhance the library's multiplatform capabilities, we would be delighted to hear from you.
